### ISSUE TITLE
still produce error when validations key is not in array

### ISSUE THREAD

**Issue by Nakira** [adamaveray/typeform#5]
```
$this->validations = $data['validations'] ?? [];
```
on https://github.com/adamaveray/typeform/blob/main/src/Models/Forms/Field.php#L27

still produce error when validations key is not in array : 
```
In Field.php line 27:
                                              
  Warning: Undefined array key "validations"
```

**Comment by adamaveray** [comment]
@Nakira That's strange, that's not possible with the null coalescing operator even with the strictest error reporting mode enabled – see https://onlinephp.io/c/430e6 & click 'execute code' for a demo. The PHP site's announcement of this feature even shows exactly what's being done here as an example: https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op. It sounds like it might be still running an older version of this package on your end. Can you open the file directly within your local `vendor` directory and confirm it's the updated version? Try running `composer update adamaveray/typeform` again to be sure.

**Comment by Nakira** [comment]
Ok, my bad... the package was not up-to-date :+1:
